name: flutter_ffi_plugin
description: A new flutter plugin project.
version: 0.0.1
author:
homepage: https://github.com/rodydavis/flutter_ffi_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  cupertino_ffi: ^0.2.1
  cupertino_ffi_generated: ^0.1.1
  ffi_tool: ^0.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  plugin:
    platforms:
      android:
        package: com.example.flutter_ffi_plugin
        pluginClass: FlutterFfiPlugin
      ios:
        pluginClass: FlutterFfiPlugin
      macos:
        pluginClass: FlutterFfiPlugin

