name: rusty_ffi_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3
  cupertino_icons: ^0.1.2
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - target/debug/
    - data/
