name: shared_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_ffi: ^0.2.1
  cupertino_ffi_generated: ^0.1.1
  ffi_tool: ^0.2.2
  ffi: ^0.1.3
  os: ^0.1.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
