name: dart_wasmer
description: A Dart Wasmer Example.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  meta: ^1.1.8
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - target/debug/
    - src/add.wasm
